### PR TITLE
Remove glyphs for codepoints U+0000-U+001F

### PR DESCRIPTION
**Pull request by Zirias**
Glyphs in this range confuse xterm to assume these were glyphs for the VT100 "DEC special graphics" mode.

---
Background is `xterm` supporting the DEC VT100 "shift out" sequences used to display 32 special line/box drawing characters, even with 7bit ASCII. The necessary glyphs are expected either at their Unicode codepoints or in the "low range" `0x00-0x1f`. If not all glyphs are available at their Unicode codepoints, but the font has glyphs for this low range, the unfortunate behavior in `xterm` is that it *only* uses the glyphs from the low range.

Because these fonts have the original IBM glyphs in this low range and these are very different from the "DEC special graphics" encoding, the result is wrong characters, e.g. when you output a `U+2592` (shade) character, codepoint `0x02` is used instead, but in IBM OEM, that's a smiley....

There are two ways to fix the fonts for `xterm`. Either add all the "DEC glyphs" at their Unicode codepoints as well (which would be questionable, many of these never existed in IBM character sets), or remove all the glyphs for the low range, which is what this patch does.

I think they don't serve any real purpose anyways. These fonts can't just be used as "8bit encoded" anyways, because the range `0x80-0xff` won't fit, so you need to translate MS-DOS texts to Unicode when using these fonts and all the glyphs are available there.

### CODE REVIEW

**Comment by marcobfvr** [comment]
Hi Zirias, thank you for your contribution! Sounds sensible, I'll test from your fork and will report back. Is this strictly an xterm quirk?

**Comment by farsil** [comment]
Hi Zirias, thank you for your contribution! Sounds sensible, I'll test from your fork and will report back. Is this strictly an xterm quirk?

**Comment by Zirias** [comment]
> Hi Zirias, thank you for your contribution! Sounds sensible, I'll test from your fork and will report back. Is this strictly an xterm quirk?

I only tested `konsole` which wasn't confused by these glyphs. As far as I understood the issue, having glyphs for this special VT100 "shift mode" in the area `00-1F` was a common thing for (X11) fonts for 8bit encodings, after all, there's room as these are all control characters. But I think the way `xterm` deals with this here can be described as "quirky" anyways. Although the fallback to `00-1F` probably makes sense, it's weird that it looks for the whole set of these glyphs there as soon as a single one isn't present at the actual Unicode codepoint...

Still I think removing them won't hurt as there's no straight-forward way to use them at these encoding positions anyways.

BTW, I'd say with these glyphs removed, xterm and these fonts are a dream team:
image

I'll probably add a port for FreeBSD soon and think about having an option (on by default) for removing the glyphs for now:
https://github.com/Zirias/zfbsd-ports/blob/local/x11-fonts/ibmfonts/Makefile

**Comment by farsil** [comment]
I checked the output of your tool with xterm, using one of the ibmfonts, and the default `fixed` font:

image

image

It would seem that all glyphs in the `0x00-0x1f` range are indeed removed (except for `0x14` and `0x15` for some reason). 

I don't mind clearing those codepoints, but I would like to understand the issue we're talking about first (mostly because I'm curious about the old times). Do you have links to some documentation? How can I reproduce the problem?

**Comment by Zirias** [comment]
> It would seem that all glyphs in the `0x00-0x1f` range are indeed removed (except for `0x14` and `0x15` for some reason).

That's a misinterpretation of the output. dos2ansi always outputs Unicode (UTF-8 by default on Linux/BSD/...), so it never uses codepoints < `U+0020` because they are reserved for control characters and won't display anything. The screenshot just shows that your "fixed" font misses many glyphs. For comparison, here's what an uncofigured `xterm` shows on my machine:
image

You can see the *real* issue when you look at CP-437 codepoint `0xb1` in your first screenshot. This *should* be a "medium shade", but it's a filled smiley instead. This is where xterm's weird behavior regarding the DEC line drawing glyphs kicks in.

> I don't mind clearing those codepoints, but I would like to understand the issue we're talking about first (mostly because I'm curious about the old times). Do you have links to some documentation? How can I reproduce the problem?

First, it's about these symbols: https://en.wikipedia.org/wiki/DEC_Special_Graphics -- A VT100-compatible terminal emulator must be able to display them when the escape sequences documented there are used. I can only guess (but it would certainly make sense) that they occupied the slots `0x00`-`0x1f` in DEC's hardware font, just because there was space available (again, this is the control character range, the terminal will never display a glyph there).

All these symbols have unicode codepoints as well. `xterm` first looks at these codepoints, which is IMHO pretty sane. But then it gets weird: If it doesn't find the full set in the font, it tries glyphs for the control character area instead if the font *has* glyphs there, exclusively. This fallback certainly makes some sense assuming "8bit fonts" used this area for these glyphs indeed. But it's weird to do the fallback for the whole set instead of just for individual glyphs. And then, it gets even weirder: This fallback also happens when you don't use the DEC escape sequence at all but instead directly try to output a unicode character. And that's the final "nail in the coffin" here: For CP-437 codepoint `0xb1`, dos2ansi translates this correctly to `U+2592` ("medium shade"), but then `xterm`'s weird fallback kicks in and actually displays the glyph for `U+0002` instead.

For comparison, the "real" smiley shown at CP-437 codepoint `0x02` is `U+263B`.

Finally, here's a somewhat relevant excerpt from `man xterm`:
```
               The VT100 line-drawing character set (also known as the DEC
               Special Character and Line Drawing Set) is shown in this table.
               It includes a few special characters which are not used for
               drawing lines:

               Cell   Unicode   Description
               ────────────────────────────────────────────────────────────
               0      U+25AE    black vertical rectangle
               1      U+25C6    black diamond
               2      U+2592    medium shade
               3      U+2409    symbol for horizontal tabulation
               4      U+240C    symbol for form feed
               5      U+240D    symbol for carriage return
               6      U+240A    symbol for line feed
               7      U+00B0    degree sign
               8      U+00B1    plus-minus sign
               9      U+2424    symbol for newline
               10     U+240B    symbol for vertical tabulation
               11     U+2518    box drawings light up and left
               12     U+2510    box drawings light down and left
               13     U+250C    box drawings light down and right
               14     U+2514    box drawings light up and right
               15     U+253C    box drawings light vertical and horizontal
               16     U+23BA    box drawings scan 1
               17     U+23BB    box drawings scan 3
               18     U+2500    box drawings light horizontal
               19     U+23BC    box drawings scan 7
               20     U+23BD    box drawings scan 9
               21     U+251C    box drawings light vertical and right
               22     U+2524    box drawings light vertical and left
               23     U+2534    box drawings light up and horizontal
               24     U+252C    box drawings light down and horizontal
               25     U+2502    box drawings light vertical
               26     U+2264    less-than or equal to
               27     U+2265    greater-than or equal to
               28     U+03C0    greek small letter pi
               29     U+2260    not equal to
               30     U+00A3    pound sign
               31     U+00B7    middle dot
               ────────────────────────────────────────────────────────────
```

Anyways, my bottom line is still: There's no way to make a terminal display glyphs for `U+0000` - `U+001F` (yep, control characters), and using them in some other software isn't very helpful either as you'll have to translate anything above `U+007F` anyways because it differs from DOS codepages, so removing the glyphs won't hurt anything but prevent the display bugs with `xterm` :)

I meanwhile added a FreeBSD port: https://www.freshports.org/x11-fonts/ibmfonts/
Removing these glyphs is an optional patch for now, but enabled by default.

**Comment by Zirias** [comment]
Rebased onto current `master` now.

For completeness the same display glitch is visible in your first screenshot for CP-437 codepoints `0xb3`, `0xb4`, `0xc0`-`0xc5`, `0xd9` and `0xda` -- so display of some actual DOS ASCII/ANSI-art file will be heavily distorted.

**Comment by farsil** [comment]
Thanks for the thorough explaination Zirias. I've done some research myself in the mean time and got to the same conclusion: those glyphs shouldn't have been there in the first place.

**Review by farsil — APPROVED** [review]

**Comment by Zirias** [comment]
Thanks a lot for the new release, this allowed me to simplify the FreeBSD port a lot:
https://cgit.freebsd.org/ports/commit/?id=903018febdf2512ae90b27cb70187f2c26e44c6e

Please don't fiddle with existing tags though. Now people still having the old port version will have it fail during "fetch". Not a big deal right now as the port isn't in any "quarterly" branch yet (where it will remain unchanged for 3 months), just a general hint that changing public tags can break things :)

**Comment by farsil** [comment]
Fair enough, I've added the old tag back for backwards compatibility.

**Pull request merged**
